### ISSUE TITLE
hello. Can you show me the config for blur background of kitty? Thank you

### ISSUE THREAD

**Issue by hungvx-dev** [BIKA-C/spade-7#2]
How can I contact you? Can we discuss https://github.com/kovidgoyal/kitty/pull/6135?

![image](https://github.com/BIKA-C/spade-7/assets/85088954/5435148e-ca28-4b46-a812-ee4974d4a991)

**Comment by trivial-zero** [comment]
Do not contact me privately in any form for this inquiry.  I am not interested in digging any deeper if he has no intention merging this system specific tweak. If you are interested, I have my fork of his kitty repo as public. Tweaking the value of [this](https://github.com/BIKA-C/kitty/blob/42daebeeac073fe13ba5327309ab1d5ab2df0fca/glfw/cocoa_window.m#L1841) line of code changes the blur radius
